sudo: false

dist: xenial

language: erlang

otp_release:
 - 20.0
 - 20.1

install: "true"

script:
  - rebar3 do compile, xref

notifications:
  slack:
    secure: "X2MF6VQENJu47gJNwU1450L70IgPgZpnWfFD0izI7uUivVZG+bo0bTYI41Hu8drQvQ69qyL/1ckNLDRQjwSn4KHqsRkQFrsjkzf79xYimCyYm0zqEjelk1xZPUD86Q7PSW9n55MVdT14iEV+81l+4BJXJcRINJulglatKgIv0syXJFlVbPBW0jTXWmt1Urq9Uq6EL47zUf8SBI0A8kZletfvyAxhsGKDBTp9r4MqQqtgOB2S6VGoU/+OVpBioXm4awKxS7pqJLDzEf3R5baXrwxI/mNSrbJlrw5cgSjEvUdptrZaRcGFbe1gzMgZ+mLby6+O1aSxaCZtf28WoxAKtwo2D8Na75uAG9naGBZc8gzKz5izjlHmBG+X02RQ2uBQZhZsMiA8L5m+yNbmtbQZFNliKZjLJVs2fAd+smLaifT9Kt9Y9M/yikRw9xktHXPFkPZCAUYyxcZu5oBC6beexwv/WAu0g4nBlPVnTAhaDwE05nhbaj1uDGHwVSOVUddDIPjfPNkkdAk30xJsVEtwYPGFz93WHgi3OahAqQESynILEFHhOn1mbVCAyj72fZxPJ4TRG6op6yJo2iX0RwIAoUkfvWv7j65DhR4HjRT+eDt3gbpzbWQsZbSbZEJkYqWDQ7Zvyz/cTK/QFWYADK3BMxNwwEClxo5NoyH0kcIrl9o="
