sudo: false

language: erlang

otp_release:
 - 19.3
 - 20.0
 - 20.1

install: "true"

before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3

script:
  - ./rebar3 do compile, xref
